"""device id tables

Revision ID: 098c6b5acd9b
Revises: 2c39382cb489
Create Date: 2019-04-21 17:02:42.822948

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '098c6b5acd9b'
down_revision = '2c39382cb489'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('GPS__module', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint('gps__module_ibfk_1', 'GPS__module', type_='foreignkey')
    op.create_foreign_key(None, 'GPS__module', 'device', ['device_id'], ['id'])
    op.drop_column('GPS__module', 'user_id')
    op.add_column('fire__sensor', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint('fire__sensor_ibfk_1', 'fire__sensor', type_='foreignkey')
    op.create_foreign_key(None, 'fire__sensor', 'device', ['device_id'], ['id'])
    op.drop_column('fire__sensor', 'user_id')
    op.add_column('humidity__sensor', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint('humidity__sensor_ibfk_1', 'humidity__sensor', type_='foreignkey')
    op.create_foreign_key(None, 'humidity__sensor', 'device', ['device_id'], ['id'])
    op.drop_column('humidity__sensor', 'user_id')
    op.add_column('image', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint('image_ibfk_1', 'image', type_='foreignkey')
    op.create_foreign_key(None, 'image', 'device', ['device_id'], ['id'])
    op.drop_column('image', 'user_id')
    op.add_column('rainfall__sensor', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint('rainfall__sensor_ibfk_1', 'rainfall__sensor', type_='foreignkey')
    op.create_foreign_key(None, 'rainfall__sensor', 'device', ['device_id'], ['id'])
    op.drop_column('rainfall__sensor', 'user_id')
    op.add_column('smoke__sensor', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint('smoke__sensor_ibfk_1', 'smoke__sensor', type_='foreignkey')
    op.create_foreign_key(None, 'smoke__sensor', 'device', ['device_id'], ['id'])
    op.drop_column('smoke__sensor', 'user_id')
    op.add_column('soil__moisture__sensor', sa.Column('device_id', sa.Integer(), nullable=True))
    op.drop_constraint('soil__moisture__sensor_ibfk_1', 'soil__moisture__sensor', type_='foreignkey')
    op.create_foreign_key(None, 'soil__moisture__sensor', 'device', ['device_id'], ['id'])
    op.drop_column('soil__moisture__sensor', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('soil__moisture__sensor', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'soil__moisture__sensor', type_='foreignkey')
    op.create_foreign_key('soil__moisture__sensor_ibfk_1', 'soil__moisture__sensor', 'device', ['user_id'], ['id'])
    op.drop_column('soil__moisture__sensor', 'device_id')
    op.add_column('smoke__sensor', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'smoke__sensor', type_='foreignkey')
    op.create_foreign_key('smoke__sensor_ibfk_1', 'smoke__sensor', 'device', ['user_id'], ['id'])
    op.drop_column('smoke__sensor', 'device_id')
    op.add_column('rainfall__sensor', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'rainfall__sensor', type_='foreignkey')
    op.create_foreign_key('rainfall__sensor_ibfk_1', 'rainfall__sensor', 'device', ['user_id'], ['id'])
    op.drop_column('rainfall__sensor', 'device_id')
    op.add_column('image', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.create_foreign_key('image_ibfk_1', 'image', 'device', ['user_id'], ['id'])
    op.drop_column('image', 'device_id')
    op.add_column('humidity__sensor', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'humidity__sensor', type_='foreignkey')
    op.create_foreign_key('humidity__sensor_ibfk_1', 'humidity__sensor', 'device', ['user_id'], ['id'])
    op.drop_column('humidity__sensor', 'device_id')
    op.add_column('fire__sensor', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'fire__sensor', type_='foreignkey')
    op.create_foreign_key('fire__sensor_ibfk_1', 'fire__sensor', 'device', ['user_id'], ['id'])
    op.drop_column('fire__sensor', 'device_id')
    op.add_column('GPS__module', sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'GPS__module', type_='foreignkey')
    op.create_foreign_key('gps__module_ibfk_1', 'GPS__module', 'device', ['user_id'], ['id'])
    op.drop_column('GPS__module', 'device_id')
    # ### end Alembic commands ###
