"""users table

Revision ID: 1b7bd43410a3
Revises: 
Create Date: 2019-04-18 16:04:16.937638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7bd43410a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_device_id'), 'device', ['device_id'], unique=True)
    op.create_table('GPS__module',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(length=10), nullable=True),
    sa.Column('longitude', sa.String(length=10), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_GPS__module_timestamp'), 'GPS__module', ['timestamp'], unique=False)
    op.create_table('fire__sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=20), nullable=True),
    sa.Column('reading', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fire__sensor_timestamp'), 'fire__sensor', ['timestamp'], unique=False)
    op.create_table('humidity__sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=20), nullable=True),
    sa.Column('reading', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_humidity__sensor_timestamp'), 'humidity__sensor', ['timestamp'], unique=False)
    op.create_table('image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bears', sa.Integer(), nullable=True),
    sa.Column('deer', sa.Integer(), nullable=True),
    sa.Column('lynx', sa.Integer(), nullable=True),
    sa.Column('wolves', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_timestamp'), 'image', ['timestamp'], unique=False)
    op.create_table('rainfall__sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=20), nullable=True),
    sa.Column('reading', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rainfall__sensor_timestamp'), 'rainfall__sensor', ['timestamp'], unique=False)
    op.create_table('smoke__sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=20), nullable=True),
    sa.Column('reading', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smoke__sensor_timestamp'), 'smoke__sensor', ['timestamp'], unique=False)
    op.create_table('soil__moisture__sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=20), nullable=True),
    sa.Column('reading', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soil__moisture__sensor_timestamp'), 'soil__moisture__sensor', ['timestamp'], unique=False)
    op.create_table('temperature__sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(length=20), nullable=True),
    sa.Column('reading', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_temperature__sensor_timestamp'), 'temperature__sensor', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_temperature__sensor_timestamp'), table_name='temperature__sensor')
    op.drop_table('temperature__sensor')
    op.drop_index(op.f('ix_soil__moisture__sensor_timestamp'), table_name='soil__moisture__sensor')
    op.drop_table('soil__moisture__sensor')
    op.drop_index(op.f('ix_smoke__sensor_timestamp'), table_name='smoke__sensor')
    op.drop_table('smoke__sensor')
    op.drop_index(op.f('ix_rainfall__sensor_timestamp'), table_name='rainfall__sensor')
    op.drop_table('rainfall__sensor')
    op.drop_index(op.f('ix_image_timestamp'), table_name='image')
    op.drop_table('image')
    op.drop_index(op.f('ix_humidity__sensor_timestamp'), table_name='humidity__sensor')
    op.drop_table('humidity__sensor')
    op.drop_index(op.f('ix_fire__sensor_timestamp'), table_name='fire__sensor')
    op.drop_table('fire__sensor')
    op.drop_index(op.f('ix_GPS__module_timestamp'), table_name='GPS__module')
    op.drop_table('GPS__module')
    op.drop_index(op.f('ix_device_device_id'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
